// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
//export const GET_PRODUCTS = "GET_PRODUCTS";
//export const GET_ORDERS = "GET_ORDERS";
//export const GET_SELLERS = "GET_SELLERS";
export const GET_REPORT_INDENT = "GET_REPORT_INDENT";
export const GET_REPORT_CANCEL_INDENT = "GET_REPORT_CANCEL_INDENT";
export const GET_REPORT_SCHEDULE_INDENT = "GET_REPORT_SCHEDULE_INDENT";
export const GET_REPORT_ORDER = "GET_REPORT_ORDER";
export const GET_REPORT_QUOTA = "GET_REPORT_QUOTA";
export const GET_REPORT_SCHEDULED = "GET_REPORT_SCHEDULED";
export const GET_USER_DATA_CODE = "GET_USER_DATA_CODE";

/**
* Add REPORT_INDENT
*/
export const ADD_NEW_REPORT_INDENT = "ADD_NEW_REPORT_INDENT";
export const ADD_REPORT_INDENT_SUCCESS = "ADD_REPORT_INDENT_SUCCESS";
export const ADD_REPORT_INDENT_FAIL = "ADD_REPORT_INDENT_FAIL";

/**
* Add CANCEL_REPORT_INDENT
*/
export const ADD_NEW_CANCEL_REPORT_INDENT = "ADD_NEW_CANCEL_REPORT_INDENT";
export const ADD_CANCEL_REPORT_INDENT_SUCCESS = "ADD_CANCEL_REPORT_INDENT_SUCCESS";
export const ADD_CANCEL_REPORT_INDENT_FAIL = "ADD_CANCEL_REPORT_INDENT_FAIL";

/**
* Add SCHEDULE_REPORT_INDENT
*/
export const ADD_NEW_SCHEDULE_REPORT_INDENT = "ADD_NEW_SCHEDULE_REPORT_INDENT";
export const ADD_SCHEDULE_REPORT_INDENT_SUCCESS = "ADD_SCHEDULE_REPORT_INDENT_SUCCESS";
export const ADD_SCHEDULE_REPORT_INDENT_FAIL = "ADD_SCHEDULE_REPORT_INDENT_FAIL";

/**
 * Edit REPORT_INDENT
 */
export const UPDATE_REPORT_INDENT = "UPDATE_REPORT_INDENT";
export const UPDATE_REPORT_INDENT_SUCCESS = "UPDATE_REPORT_INDENT_SUCCESS";
export const UPDATE_REPORT_INDENT_FAIL = "UPDATE_REPORT_INDENT_FAIL";

/**
 * Delete REPORT_INDENT
 */
export const DELETE_REPORT_INDENT = "DELETE_REPORT_INDENT";
export const DELETE_REPORT_INDENT_SUCCESS = "DELETE_REPORT_INDENT_SUCCESS";
export const DELETE_REPORT_INDENT_FAIL = "DELETE_REPORT_INDENT_FAIL";
