// Actions
export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";
//export const GET_PRODUCTS = "GET_PRODUCTS";
//export const GET_ORDERS = "GET_ORDERS";
//export const GET_SELLERS = "GET_SELLERS";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const   GET_TRANSPORTERS = "GET_TRANSPORTERS";
export const   GET_ROLES = "GET_ROLES";
export const GET_QUOTA = "GET_QUOTA";
export const   GET_VEHICLE = "GET_VEHICLE";
export const   GET_CLEANER = "GET_CLEANER";
export const   GET_CLUSTER = "GET_CLUSTER";
export const   GET_PLANT = "GET_PLANT";
export const   GET_MATERIAL = "GET_MATERIAL";
export const   GET_DRIVER = "GET_DRIVER";
export const   GET_USERS = "GET_USERS";
export const   GET_PROCESS = "GET_PROCESS";

/** * Delete ORDER
 */
//export const DELETE_ORDER = "DELETE_ORDER";
//export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
//export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

/**
* Update ORDER
*/
//export const UPDATE_ORDER = "UPDATE_ORDER";
//export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
//export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

/**
 * Add ORDER
 */
//export const ADD_NEW_ORDER = "ADD_NEW_ORDER";
//export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
//export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";

/**
* Add CUSTOMER
*/
export const ADD_NEW_CUSTOMER = "ADD_NEW_CUSTOMER";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAIL = "ADD_CUSTOMER_FAIL";

/**
* Add CLEANER
*/
export const ADD_NEW_CLEANER = "ADD_NEW_CLEANER";
export const ADD_CLEANER_SUCCESS = "ADD_CLEANER_SUCCESS";
export const ADD_CLEANER_FAIL = "ADD_CLEANER_FAIL";

/**
* Add PLANT
*/
export const ADD_NEW_PLANT = "ADD_NEW_PLANT";
export const ADD_PLANT_SUCCESS = "ADD_PLANT_SUCCESS";
export const ADD_PLANT_FAIL = "ADD_PLANT_FAIL";

/**
* Add VEHICLE
*/
export const ADD_NEW_VEHICLE = "ADD_NEW_VEHICLE";
export const ADD_VEHICLE_SUCCESS = "ADD_VEHICLE_SUCCESS";
export const ADD_VEHICLE_FAIL = "ADD_VEHICLE_FAIL";

/**
* Add DRIVER
*/
export const ADD_NEW_DRIVER = "ADD_NEW_DRIVER";
export const ADD_DRIVER_SUCCESS = "ADD_DRIVER_SUCCESS";
export const ADD_DRIVER_FAIL = "ADD_DRIVER_FAIL";

/**
* Add CLUSTER
*/
export const ADD_NEW_CLUSTER = "ADD_NEW_CLUSTER";
export const ADD_CLUSTER_SUCCESS = "ADD_CLUSTER_SUCCESS";
export const ADD_CLUSTER_FAIL = "ADD_CLUSTER_FAIL";


/**
* Add TRANSPORTER
*/
export const ADD_NEW_TRANSPORTER = "ADD_NEW_TRANSPORTER";
export const ADD_TRANSPORTER_SUCCESS = "ADD_TRANSPORTER_SUCCESS";
export const ADD_TRANSPORTER_FAIL = "ADD_TRANSPORTER_FAIL";


/**
* Add RAISE INDENt
*/
export const ADD_NEW_RAISE_INDENT = "ADD_NEW_RAISE_INDENT";
export const ADD_RAISE_INDENT_SUCCESS = "ADD_RAISE_INDENT_SUCCESS";
export const ADD_RAISE_INDENT_FAIL = "ADD_RAISE_INDENT_FAIL";


/**
* Add Quota
*/
export const ADD_NEW_QUOTA = "ADD_NEW_QUOTA";
export const ADD_QUOTA_SUCCESS = "ADD_QUOTA_SUCCESS";
export const ADD_QUOTA_FAIL = "ADD_QUOTA_FAIL";

/**
 * Edit CUSTOMER
 */
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAIL = "UPDATE_CUSTOMER_FAIL";

/**
 * Edit CLUSTER
 */
export const UPDATE_CLUSTER = "UPDATE_CLUSTER";
export const UPDATE_CLUSTER_SUCCESS = "UPDATE_CLUSTER_SUCCESS";
export const UPDATE_CLUSTER_FAIL = "UPDATE_CLUSTER_FAIL";

/**
 * Edit PLANT
 */
export const UPDATE_PLANT = "UPDATE_PLANT";
export const UPDATE_PLANT_SUCCESS = "UPDATE_PLANT_SUCCESS";
export const UPDATE_PLANT_FAIL = "UPDATE_PLANT_FAIL";

/**
 * Edit VEHICLE
 */
export const UPDATE_VEHICLE = "UPDATE_VEHICLE";
export const UPDATE_VEHICLE_SUCCESS = "UPDATE_VEHICLE_SUCCESS";
export const UPDATE_VEHICLE_FAIL = "UPDATE_VEHICLE_FAIL";

/**
 * Delete CUSTOMER
 */
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL";

/**
 * Delete VEHICLE
 */
export const DELETE_VEHICLE = "DELETE_VEHICLE";
export const DELETE_VEHICLE_SUCCESS = "DELETE_VEHICLE_SUCCESS";
export const DELETE_VEHICLE_FAIL = "DELETE_VEHICLE_FAIL";

/**
 * Delete PRODUCT
 */
//export const DELETE_PRODUCT = "DELETE_PRODUCT";
//export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
//export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

/**
* Add PRODUCT
*/
//export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
//export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
//export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

/**
 * Edit PRODUCT
 */
//export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
//export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
//export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"
